# Generated by Django 3.1.2 on 2023-01-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Devicename', models.CharField(max_length=67)),
                ('temp', models.CharField(max_length=254)),
                ('hum', models.CharField(max_length=254)),
                ('ppm', models.CharField(max_length=254)),
                ('bat', models.CharField(max_length=254)),
                ('sol', models.CharField(max_length=254)),
                ('Timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
