# Generated by Django 3.1.2 on 2023-01-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='Timestamp',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
