# Generated by Django 2.1.7 on 2020-04-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcminfo',
            name='active',
            field=models.NullBooleanField(max_length=78),
        ),
        migrations.AddField(
            model_name='fcminfo',
            name='registration_id',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='fcminfo',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fcminfo',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
