# Generated by Django 2.1.7 on 2020-04-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_userdata_notification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Notification_State',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
