# Generated by Django 2.1.7 on 2020-04-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_device_notification_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Notification_Time',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
