# Generated by Django 2.1.7 on 2020-04-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_device_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Room_Permission',
            field=models.CharField(blank=True, max_length=956, null=True),
        ),
    ]
