# Generated by Django 2.1.7 on 2020-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_device_heavy_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Heavy_Time',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
