# Generated by Django 3.0.6 on 2020-06-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20200616_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Devicenumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
