# Generated by Django 3.0.6 on 2020-06-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_device_typedc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='TypedC',
        ),
    ]
