# Generated by Django 3.0.6 on 2020-07-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_remove_device_typedc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TreeName', models.CharField(max_length=100)),
                ('TreeParent', models.CharField(max_length=13)),
                ('TreeId', models.CharField(blank=True, max_length=254, null=True)),
                ('TreeImage', models.CharField(blank=True, max_length=254, null=True)),
                ('TreeWeight', models.CharField(blank=True, max_length=254, null=True)),
                ('TreeHeight', models.CharField(blank=True, max_length=254, null=True)),
                ('TreeDetails', models.CharField(blank=True, max_length=254, null=True)),
                ('TreeLocation', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
