# Generated by Django 3.0.6 on 2020-07-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='TreePlantedDate',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
