# Generated by Django 3.0.6 on 2020-07-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_tree_treeplanteddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeEmploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployParent', models.CharField(max_length=13)),
                ('EmployState', models.CharField(blank=True, max_length=254, null=True)),
                ('EmployType', models.CharField(blank=True, max_length=254, null=True)),
                ('EmployAddedBy', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreeUser',
            fields=[
                ('TreeUserNumber', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tree',
            name='TreeUser',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
