# Generated by Django 3.0.6 on 2020-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_auto_20200716_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeuser',
            name='TreeUserName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treeemploy',
            name='EmployParent',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
