# Generated by Django 3.0.6 on 2020-08-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_auto_20200717_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeTwitterUser',
            fields=[
                ('TreeTwitterUserTag', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('TreeTwitterUserName', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
