# Generated by Django 3.0.6 on 2020-08-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0019_treetwitteruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treetwitteruser',
            old_name='TreeTwitterUserName',
            new_name='TreeTwitterUserId',
        ),
    ]
