# Generated by Django 3.0.6 on 2020-08-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_auto_20200804_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwitterTreeUser',
            new_name='TwitterUser',
        ),
    ]
