# Generated by Django 3.0.6 on 2020-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0023_auto_20200804_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='TreeTwitterCount',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='TreeTwitterProfile',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='TreeTwitterTagLine',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='TreeTwitterUserId',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='TreeTwitterUserTag',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='TwitterCount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='TwitterProfile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='TwitterTagLine',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='TwitterUserId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='TwitterUserTag',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
