# Generated by Django 3.0.6 on 2020-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0024_auto_20200804_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUserNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TwitterUserTag', models.CharField(max_length=50)),
                ('TwitterUserId', models.CharField(blank=True, max_length=100, null=True)),
                ('TwitterTagLine', models.CharField(blank=True, max_length=1000, null=True)),
                ('TwitterProfile', models.CharField(blank=True, max_length=100, null=True)),
                ('TwitterCount', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
