# Generated by Django 3.0.6 on 2020-08-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_twitterusernew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
