# Generated by Django 3.0.6 on 2020-08-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0027_twitteruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwitterUserNew',
        ),
    ]
