# Generated by Django 3.0.6 on 2020-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0028_delete_twitterusernew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='TwitterCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
