# Generated by Django 3.0.6 on 2020-09-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0029_auto_20200804_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='TwitterProfile',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
