# Generated by Django 3.1.1 on 2020-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0030_auto_20200908_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimation',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='underprocess',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='updated',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fcminfo',
            name='active',
            field=models.BooleanField(blank=True, max_length=78, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Is_authenticated',
            field=models.BooleanField(blank=True, max_length=78, null=True),
        ),
    ]
