# Generated by Django 3.1.1 on 2020-10-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0031_auto_20200922_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Door',
        ),
        migrations.DeleteModel(
            name='Gate',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
