# Generated by Django 3.1.3 on 2020-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0034_auto_20201109_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RemoteACKey',
        ),
        migrations.RemoveField(
            model_name='remotecompanyname',
            name='company_name_id',
        ),
        migrations.RemoveField(
            model_name='remotecompanyname',
            name='created_by_id',
        ),
        migrations.RemoveField(
            model_name='remotecompanyname',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='remotecompanyname',
            name='product_name_id',
        ),
        migrations.RemoveField(
            model_name='remotecompanyname',
            name='swing_off',
        ),
        migrations.RemoveField(
            model_name='remotecompanyname',
            name='swing_on',
        ),
        migrations.RemoveField(
            model_name='remotecompanyname',
            name='updated_by_id',
        ),
        migrations.RemoveField(
            model_name='remotecompanyname',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='userdata',
            name='Response_Data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
