# Generated by Django 3.1.3 on 2020-11-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0037_auto_20201109_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Response',
            field=models.CharField(blank=True, max_length=10056, null=True),
        ),
    ]
