# Generated by Django 3.1.3 on 2020-11-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0038_auto_20201109_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
