# Generated by Django 3.1.3 on 2020-11-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0039_auto_20201109_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='Response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
