# Generated by Django 3.1.3 on 2020-11-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0040_auto_20201109_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotetvkey',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='remotetvkey',
            name='update_date',
        ),
    ]
