# Generated by Django 3.1.3 on 2020-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0041_auto_20201109_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteDTH',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('protocol', models.CharField(blank=True, max_length=1800, null=True)),
                ('power_on_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('power_off_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('up_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('down_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('volume_up_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('volume_down_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('zero_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('one_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('two_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('three_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('four_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('five_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('six_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('seven_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('eight_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('nine_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('channel_down_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('channel_up_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('exit_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('left_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('menu_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('mute_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('right_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('select_button', models.CharField(blank=True, max_length=1800, null=True)),
                ('company_name_id', models.CharField(blank=True, max_length=1800, null=True)),
                ('product_name_id', models.CharField(blank=True, max_length=1800, null=True)),
            ],
        ),
    ]
