# Generated by Django 3.1.3 on 2020-11-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0042_remotedth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotedth',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
