# Generated by Django 3.1.3 on 2020-11-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0043_auto_20201110_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoomInfo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Response', models.TextField(blank=True, null=True)),
                ('ImagePath', models.TextField(blank=True, null=True)),
                ('NamePath', models.TextField(blank=True, null=True)),
                ('Count', models.IntegerField(blank=True, default=0, null=True)),
                ('UserNumber', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='remotedth',
            name='brand_name',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
    ]
