# Generated by Django 3.1.3 on 2020-11-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0044_auto_20201110_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Assigned_Info',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
