# Generated by Django 3.1.3 on 2020-11-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0045_device_assigned_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Assigned_Info',
            field=models.CharField(default=['0off', '1off', '2off', '3off', '4off', '5off', '6off', '7off'], max_length=256),
            preserve_default=False,
        ),
    ]
