# Generated by Django 3.1.3 on 2020-11-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0046_auto_20201111_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Assigned_State',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
