# Generated by Django 3.1.3 on 2020-11-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0049_auto_20201112_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroominfo',
            name='Count',
        ),
    ]
