# Generated by Django 3.1.3 on 2020-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0050_remove_userroominfo_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRButtonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_id', models.TextField(blank=True, null=True)),
                ('product_name_id', models.TextField(blank=True, null=True)),
                ('brand_name', models.CharField(max_length=56)),
                ('protocol', models.CharField(max_length=56)),
                ('repeat_count', models.CharField(max_length=3)),
                ('button1', models.TextField(blank=True, null=True)),
                ('button2', models.TextField(blank=True, null=True)),
                ('button3', models.TextField(blank=True, null=True)),
                ('button4', models.TextField(blank=True, null=True)),
                ('button5', models.TextField(blank=True, null=True)),
                ('button6', models.TextField(blank=True, null=True)),
                ('button7', models.TextField(blank=True, null=True)),
                ('button8', models.TextField(blank=True, null=True)),
                ('button9', models.TextField(blank=True, null=True)),
                ('button10', models.TextField(blank=True, null=True)),
                ('button11', models.TextField(blank=True, null=True)),
                ('button12', models.TextField(blank=True, null=True)),
                ('button13', models.TextField(blank=True, null=True)),
                ('button14', models.TextField(blank=True, null=True)),
                ('button15', models.TextField(blank=True, null=True)),
                ('button16', models.TextField(blank=True, null=True)),
                ('button17', models.TextField(blank=True, null=True)),
                ('button18', models.TextField(blank=True, null=True)),
                ('button19', models.TextField(blank=True, null=True)),
                ('button20', models.TextField(blank=True, null=True)),
                ('button21', models.TextField(blank=True, null=True)),
                ('button22', models.TextField(blank=True, null=True)),
                ('button23', models.TextField(blank=True, null=True)),
                ('button24', models.TextField(blank=True, null=True)),
                ('button25', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IRDevice',
            fields=[
                ('DeviceName', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('ParentId', models.CharField(blank=True, max_length=342, null=True)),
                ('LastRequested', models.DateTimeField(blank=True, null=True)),
                ('PublishedData', models.CharField(blank=True, max_length=342, null=True)),
                ('DeviceCompanyName', models.CharField(blank=True, max_length=346, null=True, unique=True)),
                ('Assigned_State', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IRRoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.TextField(blank=True, null=True)),
                ('ImagePath', models.TextField(blank=True, null=True)),
                ('NamePath', models.TextField(blank=True, null=True)),
                ('UserNumber', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='RemoteACTwo',
        ),
        migrations.DeleteModel(
            name='RemoteCompanyName',
        ),
        migrations.DeleteModel(
            name='RemoteDTH',
        ),
        migrations.DeleteModel(
            name='RemoteProductName',
        ),
        migrations.DeleteModel(
            name='RemoteTVKey',
        ),
    ]
