# Generated by Django 3.1.3 on 2020-12-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0051_auto_20201118_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='IR_Permission',
            field=models.CharField(blank=True, max_length=956, null=True),
        ),
    ]
