# Generated by Django 3.1.3 on 2020-12-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0052_userdata_ir_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='irdevice',
            name='rooms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
