# Generated by Django 3.1.3 on 2020-12-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0053_irdevice_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='irroominfo',
            name='DeviceId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irroominfo',
            name='PubData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
