# Generated by Django 3.1.3 on 2020-12-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0054_auto_20201203_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='irroominfo',
            name='SubData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
