# Generated by Django 3.1.4 on 2020-12-06 11:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0055_irroominfo_subdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estimation',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Response_Data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
