# Generated by Django 3.1.2 on 2021-01-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0056_auto_20201206_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloneDevice',
            fields=[
                ('DeviceName', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('ParentId', models.CharField(blank=True, max_length=342, null=True)),
                ('IsActive', models.BooleanField(blank=True, max_length=45)),
                ('RequestCount', models.IntegerField(blank=True, default=0, null=True)),
                ('LastRequested', models.DateTimeField(blank=True, null=True)),
                ('DeviceNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('DeviceCompanyName', models.CharField(blank=True, max_length=346, null=True, unique=True)),
                ('ParentDevice', models.CharField(blank=True, max_length=342, null=True)),
            ],
        ),
    ]
