# Generated by Django 3.1.2 on 2021-01-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0057_clonedevice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloneDevice',
            new_name='TouchCloneDevice',
        ),
    ]
