# Generated by Django 3.1.2 on 2021-04-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0059_userdata_rgb_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dealer_number', models.CharField(max_length=13)),
                ('Dealer_customer_number', models.CharField(max_length=13)),
                ('Dealer_device', models.CharField(blank=True, max_length=56, null=True)),
                ('Dealer_device_state', models.BooleanField(blank=True, max_length=78, null=True)),
            ],
        ),
    ]
