# Generated by Django 3.1.2 on 2021-04-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0060_dealerdevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rgb',
            name='RGB_Namer',
        ),
    ]
