# Generated by Django 3.1.2 on 2021-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0061_remove_rgb_rgb_namer'),
    ]

    operations = [
        migrations.AddField(
            model_name='irbuttoninfo',
            name='IRType',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irroominfo',
            name='IRType',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
    ]
