# Generated by Django 3.1.2 on 2021-09-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0064_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
