# Generated by Django 3.1.2 on 2022-01-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0067_auto_20220102_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOAuth',
        ),
    ]
