# Generated by Django 3.1.2 on 2022-02-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0069_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemiCloneDevice',
            fields=[
                ('DeviceName', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('ParentId', models.CharField(blank=True, max_length=342, null=True)),
                ('Publisheddata', models.CharField(blank=True, max_length=342, null=True)),
                ('RequestCount', models.IntegerField(blank=True, default=0, null=True)),
                ('LastRequested', models.DateTimeField(blank=True, null=True)),
                ('DeviceNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('DeviceCompanyName', models.CharField(blank=True, max_length=346, null=True, unique=True)),
                ('ActionDevice', models.CharField(blank=True, max_length=342, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='Device_State',
            field=models.CharField(blank=True, default='[0,0,0,0,0,0,0,0]', max_length=256),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
