# Generated by Django 3.1.2 on 2022-02-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0070_auto_20220220_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Device_State',
            field=models.CharField(blank=True, default='["0","0","0","0","0","0","0","0"]', max_length=256),
        ),
    ]
