# Generated by Django 3.1.2 on 2022-02-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0071_auto_20220220_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Device_State',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
