# Generated by Django 3.1.2 on 2022-02-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0072_auto_20220220_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='Is_authenticated',
            new_name='is_anonymous',
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_authenticated',
            field=models.BooleanField(blank=True, max_length=78, null=True),
        ),
    ]
