# Generated by Django 3.1.2 on 2022-02-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0073_auto_20220227_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='is_anonymous',
            new_name='Is_authenticated',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_authenticated',
        ),
    ]
