# Generated by Django 3.1.2 on 2022-07-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0075_auto_20220707_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerdevice',
            name='D_user',
            field=models.CharField(blank=True, max_length=342, null=True),
        ),
    ]
