# Generated by Django 3.1.2 on 2022-07-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0076_dealerdevice_d_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerUsers',
            fields=[
                ('D_user', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('DealerId', models.CharField(blank=True, max_length=342, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dealerdevice',
            old_name='D_user',
            new_name='DealerId',
        ),
        migrations.RemoveField(
            model_name='dealerdevice',
            name='ParentId',
        ),
    ]
