# Generated by Django 3.1.2 on 2022-07-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0077_auto_20220707_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Imagepath',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='Namer',
            field=models.CharField(blank=True, max_length=176, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='Work',
            field=models.CharField(blank=True, max_length=176, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, max_length=176, null=True),
        ),
    ]
