# Generated by Django 3.1.2 on 2022-07-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0078_auto_20220710_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='ProfileImg',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
