# Generated by Django 3.1.2 on 2022-07-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0079_auto_20220710_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMInfo',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
        migrations.DeleteModel(
            name='TreeEmploy',
        ),
        migrations.DeleteModel(
            name='TreeUser',
        ),
        migrations.DeleteModel(
            name='TwitterTree',
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
