# Generated by Django 3.1.2 on 2022-09-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0081_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('Customer_Name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Customer_Number', models.CharField(blank=True, max_length=12, null=True)),
                ('Customer_requirement', models.CharField(blank=True, max_length=1100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
