# Generated by Django 3.1.2 on 2022-11-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0083_device_device_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Device_Icon',
            field=models.CharField(blank=True, default='["bulb01.svg","bulb01.svg","bulb01.svg","bulb01.svg","bulb01.svg","bulb01.svg"]', max_length=2256, null=True),
        ),
    ]
