# Generated by Django 3.1.2 on 2022-11-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0084_auto_20221113_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Device_Icon',
        ),
        migrations.AddField(
            model_name='device',
            name='Icons',
            field=models.CharField(blank=True, default='["bulb01.svg","bulb01.svg","bulb01.svg","bulb01.svg","bulb01.svg","bulb01.svg","bulb01.svg","bulb01.svg"]', max_length=2256, null=True),
        ),
    ]
