# Generated by Django 3.1.2 on 2022-11-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0085_auto_20221113_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='Icons',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
