# Generated by Django 3.1.2 on 2022-11-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0086_auto_20221113_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='Icons',
        ),
        migrations.AddField(
            model_name='device',
            name='Device_Icons',
            field=models.CharField(blank=True, default='["https://gthink-images-website.s3.ap-south-1.amazonaws.com/svg/bulb01.svg","https://gthink-images-website.s3.ap-south-1.amazonaws.com/svg/bulb01.svg","https://gthink-images-website.s3.ap-south-1.amazonaws.com/svg/bulb01.svg","https://gthink-images-website.s3.ap-south-1.amazonaws.com/svg/bulb01.svg","https://gthink-images-website.s3.ap-south-1.amazonaws.com/svg/bulb01.svg","https://gthink-images-website.s3.ap-south-1.amazonaws.com/svg/bulb01.svg"]', max_length=2256, null=True),
        ),
    ]
